Scheduler wasa
PSMRI/Scheduler-UI pull request #43
Opened 2024-11-30 07:38 UTC by NKOKKILIGADDA87

## 📋 Description

JIRA ID: 

Please provide a summary of the change and the motivation behind it. Include relevant context and details.

---

## ✅ Type of Change

- [ ] 🐞 **Bug fix** (non-breaking change which resolves an issue)
- [ ] ✨ **New feature** (non-breaking change which adds functionality)
- [ ] 🔥 **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🛠 **Refactor** (change that is neither a fix nor a new feature)
- [ ] ⚙️ **Config change** (configuration file or build script updates)
- [ ] 📚 **Documentation** (updates to docs or readme)
- [ ] 🧪 **Tests** (adding new or updating existing tests)
- [ ] 🎨 **UI/UX** (changes that affect the user interface)
- [ ] 🚀 **Performance** (improves performance)
- [ ] 🧹 **Chore** (miscellaneous changes that don't modify src or test files)

---

## ℹ️ Additional Information

Please describe how the changes were tested, and include any relevant screenshots, logs, or other information that provides additional context.

2024-11-30 08:04 UTC, sandipkarmakar3 commented
@coderabbitai review

2024-11-30 08:05 UTC, sandipkarmakar3 commented
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2024-12-16 08:56 UTC, drtechie commented on src/environments/environment.development.ts
> +const sessionStorageEncKey = '<%= SESSION_STORAGE_ENC_KEY %>';
@NKOKKILIGADDA87 please refer to how it's done in other places. 
This notation is only required in the ci template.
Please leave it empty in other env files.

2024-12-16 09:12 UTC, sandipkarmakar3 commented on src/environments/environment.development.ts
> +const sessionStorageEncKey = '<%= SESSION_STORAGE_ENC_KEY %>';
ok, so we'll keep the same line only in "ci template" and other environment files will have like below
const sessionStorageEncKey = <>;
is that correct? @drtechie

2024-12-16 09:32 UTC, drtechie commented on src/environments/environment.development.ts
> +const sessionStorageEncKey = '<%= SESSION_STORAGE_ENC_KEY %>';
Yes, that's fine.
Only ci.template passes through the build script (check scripts folder) where the pattern is replaced by an environment variable set in CI.

2025-01-23 08:44 UTC, sandipkarmakar3 reviewed
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-31 11:28 UTC, devikasuresh20 requested changes

2025-01-31 11:28 UTC, devikasuresh20 commented on src/environments/environment.development.ts
> +const COMMON_API_OPEN = `${commonIP}commonapi-1.0/`;
@sandipkarmakar3 Please keep common api version as "v1.0"

2025-01-31 11:31 UTC, sandipkarmakar3 commented on src/environments/environment.development.ts
> +const COMMON_API_OPEN = `${commonIP}commonapi-1.0/`;
done

2025-01-31 11:33 UTC, merged